### ISSUE TITLE
Highlight IR coverage?

### ISSUE THREAD

**Issue by adrianherrera** [ForAllSecure/bncov#11]
Hey folks!

First, super-useful plugin.

I'm curious at how easy it would be to extend the coverage highlighting to the various IRs (LLIL, HLIL, etc.). I don't know much about the Binja API, but it would be nice to see coverage when doing RE on the IRs (and not just the disassembly).

If this is straightforward, I am happy to have a go at implementing this myself!

**Comment by seeinglogic** [comment]
Thanks for trying it out!

The good news is that for everything except HLIL, the block coverage highlights should automatically transfer as shown in the screenshot of split-views (clockwise from upper left: disasm, LLIL, MLIL, HLIL).

<img width="1449" alt="default" src="https://github.com/ForAllSecure/bncov/assets/114260378/3c6a3979-ec74-47c2-a9ab-fed805a636fe">

For HLIL, since there aren't 1-to-1 mappings between disassembly and HLIL basic blocks, you can't automatically transfer block highlights. But you can approximate it by mapping coverage highlights from basic blocks onto the instructions themselves, and Binary Ninja figures out the rest.

The snippet from [here](https://mechanicalnull.github.io/prime-snips/#bncov-translate-block-highlight-to-instructions-enable-hlil-highlight) does this, so in the interactive Python console do:

```python
>>> import bncov
>>> def transfer_highlights_to_instructions(covdb: bncov.CoverageDB):
...     bv = covdb.bv
...     for block_address in covdb.total_coverage:
...         for block in bv.get_basic_blocks_starting_at(block_address):
...             cur_highlight = block.highlight
...             block.set_user_highlight(HighlightStandardColor.NoHighlightColor)
...             cur_function = block.function
...             cur_addr = block.start
...             for cur_token, cur_inst_size in block:
...                 cur_function.set_user_instr_highlight(cur_addr, cur_highlight)
...                 cur_addr += cur_inst_size
... 
>>> covdb = bncov.get_covdb(bv)
>>> transfer_highlights_to_instructions(covdb)
```

Which doesn't look as nice in graph view, but it works for HLIL and looks fine in linear view.

<img width="1450" alt="transferred" src="https://github.com/ForAllSecure/bncov/assets/114260378/6b63db41-d1af-46a4-b106-91603de47076">

Hope this helps, let me know if there's any other questions or issues you have with it!

**Comment by adrianherrera** [comment]
Woooo amazing! Thanks for the prompt and incredibly-useful reply!
